TDL-21558 Feature/incremental limit
singer-io/tap-oracle pull request #35
Opened 2023-01-04 21:37 UTC by dsprayberry

# Description of change
Adds an incremental limit feature to the tap that is version agnostic.

# Manual QA steps
 - Tested with cloned connection
 
# Risks
 - Low
 
# Rollback steps
 - revert this branch

2023-01-06 19:32 UTC, luandy64 requested changes
I want to be pickier and have the lines be 100 characters max, but I think it would really hurt the readability here. So outside of that, just the one change to the logging and I'll approve

2023-01-06 20:35 UTC, dsprayberry commented on tap_oracle/__init__.py
> +                  stream.tap_stream_id, replication_key, int(incremental_limit))
Corrected

2023-01-06 20:49 UTC, luandy64 approved these changes

2023-01-17 18:40 UTC, leslievandemark approved these changes

2023-01-24 20:00 UTC, merged