Set `utf-8` encoding while connecting to the oracle DB
singer-io/tap-oracle pull request #41
Opened 2024-06-04 08:28 UTC by sgandhi1311

This pull request addresses an issue where special characters (e.g., Japanese characters) in Oracle database tables are not retrieved correctly, resulting in data discrepancies.

# Problem Description
When connecting to an Oracle database, the Oracle tap does not set the encoding to `UTF-8` by default. This can cause special characters, such as Japanese characters, to be retrieved as `?` instead of their actual values. This issue can lead to data discrepancies and affect the accuracy of the extracted data.
Also to write those special characters, the function parameter (=**ensure_ascii**) needs to set **False** within the json.dumps function.

# Solution

- To resolve this issue, this pull request sets the `UTF-8` encoding while connecting to the Oracle database. This ensures that special characters are retrieved correctly and accurately.
- To ensure proper handling of special characters when converting data to JSON, we also set the **ensure_ascii=False** parameter within the **json.dumps** function. This parameter prevents the function from escaping non-ASCII characters.

# Changes Made

- Set the UTF-8 encoding while connecting to the Oracle database.

# Manual QA steps
 - Verified that special characters are retrieved correctly and accurately.
 
# Risks
 - No significant risks
 
# Rollback steps
 - revert this branch

2024-08-05 10:38 UTC, RushiT0122 commented on tap_oracle/db.py
>      return conn
```suggestion
    conn = cx_Oracle.connect(config["user"], 
                             config["password"], 
                             make_dsn(config), 
                             encoding='UTF-8')     # Specify the encoding for the connection
    return conn
```

2024-08-05 10:46 UTC, RushiT0122 commented on tap_oracle/sync_strategies/incremental.py
> +import tap_oracle.sync_strategies.helper as helper
```suggestion
from tap_oracle.sync_strategies import common
from tap_oracle.sync_strategies import helper
```

2024-08-05 10:47 UTC, RushiT0122 commented on tap_oracle/sync_strategies/log_miner.py
> +import tap_oracle.sync_strategies.helper as helper
```suggestion
from tap_oracle.sync_strategies import common
from tap_oracle.sync_strategies import helper
```

2024-08-05 10:54 UTC, RushiT0122 commented on tap_oracle/sync_strategies/helper.py
> +    sys.stdout.flush()
Any reason we are defining new methods than overwrting implementation in singer-python?

2024-08-05 11:01 UTC, RushiT0122 requested changes
This may not be directly related, but could we remove the pdb import from all tap code in a separate pull request?

2024-08-05 11:04 UTC, RushiT0122 commented on tap_oracle/sync_strategies/helper.py
> +    sys.stdout.flush()
https://github.com/singer-io/singer-python/blob/master/singer/messages.py#L225

2024-08-21 10:41 UTC, sgandhi1311 commented on tap_oracle/db.py
>      return conn
Done

2024-08-21 10:44 UTC, RushiT0122 approved these changes

2024-08-21 10:53 UTC, RushiT0122 commented
Please fix the cci config.

2024-08-29 12:49 UTC, RushiT0122 approved these changes

2024-08-29 12:52 UTC, merged